name: bob
version: 1.2.0.5

dependencies:
  - base >= 4.2 && < 5
  - text # added here


library:
  exposed-modules: Bob
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - bob
      - hspec
