name: acronym
version: 1.2.0.4

dependencies:
  - base

library:
  exposed-modules: Acronym
  source-dirs: src
  dependencies:
    - regex-posix
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - acronym
      - hspec
